### ISSUE TITLE
[Feature] Make the button read "Copied" when the image URL is copied

### ISSUE THREAD

**Issue by Deveesh-Shetty** [HeimanPictures/PicDB-UI#2]
Currently, If i copy the url the button reads copy itself which is little ambiguous

When we copy change the button text to "Copied"

![Screenshot_779](https://github.com/HeimanPictures/PicDB-UI/assets/89470104/867a44a1-6fd0-4777-8792-0c92cc033308)

**Comment by HeimanPictures** [comment]
Hello @a-aar0n47, your free to do it. But, please do provide a screenshot to view the added feature, before I pull it.
Thank you for your time

**Comment by Deveesh-Shetty** [comment]
It is a React project u can find the home page code at `src/pages/Home.js`

Scroll down and u will find the HTML (JSX) code

JSX is basically u can write javascript within react, it one of the feature of React.

If you are still confused don't be afraid to ask questions we will help u out :)

**Comment by a-aar0n47** [comment]
> It is a React project u can find the home page code at `src/pages/Home.js`
> 
> Scroll down and u will find the HTML (JSX) code
> 
> JSX is basically u can write javascript within react, it one of the feature of React.
> 
> If you are still confused don't be afraid to ask questions we will help u out :)

Ah, I see.
Sorry, but I'm not familiar with React and its syntax but I could complete this task using normal ES6 JavaScript. Is that okay?

**Comment by Deveesh-Shetty** [comment]
You work on the fix, If there is anything to change with respect to react we will help with that.

**Comment by a-aar0n47** [comment]
> You work on the fix, If there is anything to change with respect to react we will help with that.

Alright. Thanks!

**Comment by HeimanPictures** [comment]
@a-aar0n47 Do send a message after pushing the code.

**Comment by a-aar0n47** [comment]
> @a-aar0n47 Do send a message after pushing the code.

Yes, I have

**Comment by HeimanPictures** [comment]
@a-aar0n47 You haven't send any pull request. Check it once again

**Comment by a-aar0n47** [comment]
> @a-aar0n47 You haven't send any pull request. Check it once again

Let me have a look,

**Comment by a-aar0n47** [comment]
I am having some errors with Vercel Bot, it is refusing deployment

**Comment by a-aar0n47** [comment]
@Deveesh-Shetty 
I have fixed the bug and confirmed that it it works without any errors or bugs, but Vercel Bot is refusing pull request, please help

**Comment by Deveesh-Shetty** [comment]
Yea it even happened for my last PR....I will check it once I reach home @HeimanPictures check with the Vercel deployment once, I can't view it

**Comment by a-aar0n47** [comment]
@Deveesh-Shetty Alright

**Comment by HeimanPictures** [comment]
Ok
